require('telescope').load_extension('projects')
local tb = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', tb.find_files, { desc = 'Find files' })
vim.keymap.set('n', '<C-p>',     tb.git_files,   { desc = 'Git files' })
vim.keymap.set('n', '<leader>ps', function()
  tb.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = 'Grep string' })
vim.keymap.set('n', '<leader>op', function()
  require('telescope').extensions.projects.projects({})
end, { desc = 'Projects picker' })
